def help:
    print("============= HELP =============")
    print("'(A)' artinya hanya dapat diakses oleh admin,'(U)' artinya hanya dapat diakses oleh user, dan '(S)' artinya hanya dapat diakses oleh semuanya ")
    print("register - untuk melakukan registrasi user baru (A)")
    print("login - untuk melakukan login ke dalam sistem (S)")
    print("carirarity - untuk mencari data gadget berdasarkan rarity (S)")
    print("caritahun - untuk mencari data gadget berdasarkan tahun ditemukan (S)")
    print("tambahitem - untuk melakukan penambahan item baru (A)")
    print("hapusitem - untuk menghapus item dari database (A)")
    print("ubahjumlah - untuk mengubah jumlah item pada database (A)")
    print("pinjam - untuk meminjam gadget dari database (U)")
    print("kembalikan - untuk mengembalikan gadget yang dipinjam (U)")
    print("minta - untuk meminta consumables dari database (U)")
    print("riwayatpinjam - untuk melihat riwayat peminjaman gadget (A)")
    print("riwayatkembali - untuk melihat riwayat pengembalian gadget (A)")
    print("riwayatambil - untuk melihat riwayat pengambilan consumable (A)")
    print("save - untuk melakukan penyimpanan data (S)")
    print("help - untuk melihat bantuan (S)")
    print("exit - untuk keluar dari program (S)")